services:
  theboard.api:
    image: theboard.api
    build:
      context: .
      dockerfile: TheBoard.API/Dockerfile
    ports:
      - "27035:8080"
    volumes:
        - db-data:/app/db
  theboard.client:
    image: theboard.client
    build:
      context: TheBoard.Client/theboard-client/
      dockerfile: dockerfile
    ports:
      - "27036:8080"
    depends_on:
      - theboard.api

volumes:
  db-data: