services:
  theboard.api:
    image: theboard.api
    build:
      context: .
      dockerfile: TheBoard.API/Dockerfile
    ports:
      - "9000:8080"
    volumes:
        - ./db:/app/db
  theboard.client:
    image: theboard.client
    build:
      context: TheBoard.Client/theboard-client/
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - theboard.api
